// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: hww.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HwwServiceClient is the client API for HwwService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HwwServiceClient interface {
	Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type hwwServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHwwServiceClient(cc grpc.ClientConnInterface) HwwServiceClient {
	return &hwwServiceClient{cc}
}

func (c *hwwServiceClient) Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.HwwService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HwwServiceServer is the server API for HwwService service.
// All implementations must embed UnimplementedHwwServiceServer
// for forward compatibility
type HwwServiceServer interface {
	Hello(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedHwwServiceServer()
}

// UnimplementedHwwServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHwwServiceServer struct {
}

func (UnimplementedHwwServiceServer) Hello(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedHwwServiceServer) mustEmbedUnimplementedHwwServiceServer() {}

// UnsafeHwwServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HwwServiceServer will
// result in compilation errors.
type UnsafeHwwServiceServer interface {
	mustEmbedUnimplementedHwwServiceServer()
}

func RegisterHwwServiceServer(s grpc.ServiceRegistrar, srv HwwServiceServer) {
	s.RegisterService(&HwwService_ServiceDesc, srv)
}

func _HwwService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HwwServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HwwService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HwwServiceServer).Hello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// HwwService_ServiceDesc is the grpc.ServiceDesc for HwwService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HwwService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HwwService",
	HandlerType: (*HwwServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _HwwService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hww.proto",
}
